templateDir: openapi
globalProperties:
  apis: ""
  models: ""
additionalProperties:
  modelPropertyNaming: original
files:
  model.mustache:
    templateType: Model
    destinationFilename: .ts
  apis.mustache:
    templateType: API
    destinationFilename: .ts
